version: "3.8"
services:
  premium-realty:
    image: ghcr.io/sksahilhaque/real-estate-end-to-end-ci-cd-project:develop
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - premium-realty