name: Real Estate CI/CD

on:
  push:
    branches: ['main', 'develop', 'feature/initial-setup']
  pull_request:
    branches: ['main']

permissions:
  contents: read
  security-events: write
  actions: read
  deployments: write
  packages: write

env:
  NODE_VERSION: '22'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Prettier check
        run: npx prettier --check .
      - name: Type checking
        run: npx tsc --noEmit
      - name: Security audit
        run: npm audit --audit-level=high

  security-scan:
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'

  build-test:
    needs: [quality-check, security-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build application
        run: npm run build

      - name: Verify build output
        run: ls -la .next/

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/feature/initial-setup'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker service
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER

      - name: Set up Docker Buildx
        run: |
          sudo docker buildx create --name mybuilder --use
          sudo docker buildx inspect --bootstrap

      - name: Log in to Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          TAG="${{ env.REGISTRY }}/$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]'):${{ github.ref_name }}"
          sudo docker buildx build \
            --platform linux/amd64 \
            --push \
            --build-arg NEXT_TELEMETRY_DISABLED=1 \
            --tag "$TAG" \
            .

      - name: Test Application using Nginx
        run: |
          TAG="${{ env.REGISTRY }}/$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]'):${{ github.ref_name }}"

          cat > docker-compose.test.yml << EOF
          version: '3.8'
          services:
            premium-realty:
              image: "$TAG"
              ports:
                - '3000'
              environment:
                - NODE_ENV=production
                - PORT=3000
                - NEXT_TELEMETRY_DISABLED=1
            nginx:
              image: nginx:alpine
              ports:
                - '80:80'  # Only port accessible from outside
              volumes:
                - ./nginx.conf:/etc/nginx/nginx.conf
              depends_on:
                - premium-realty
          EOF

          sudo docker pull "$TAG"
          sudo docker-compose -f docker-compose.test.yml up -d

          sleep 20

          curl -f http://localhost:80 || exit 1

          sudo docker-compose -f docker-compose.test.yml ps

          sudo docker-compose -f docker-compose.test.yml down
          sudo docker-compose -f docker-compose.test.yml rm -f

  # Deploy to Staging
  deploy-staging:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment"
          # kubectl apply commands would go here

  # Deploy to Production
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production environment"
          # kubectl apply commands would go here
