name: Dependency Updates

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Update Dependencies
        run: |
          npm update
          npm audit fix --audit-level=high

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'Automated Dependency Updates'
          body: 'Automated dependency updates with security fixes'
          branch: 'automated/dependency-updates'
